baseURL: "http://example.org/"
languageCode: "en-us"
title: "Sangam Theme"
theme: "sangam"
themesdir: "../.."
params: 
  subtitle: "Hugo Theme For Business"
menu:
  main:
      - Name: "Home"
        Identifier: "home"
        URL: "/"
        weight: 111
        Pre: "icon-home"
      - Name: "About"
        Identifier: "about"
        URL: "/pages/about/"
        weight: 222
        Pre: "icon-about"
      - Name: "Research"
        Identifier: "research"
        URL: "/research/"
        weight: 333
        Pre: "icon-research"
      - Name: "Contact"
        Identifier: "contact"
        URL: "/pages/contact/"
        weight: 444
        Pre: "icon-contact"
      - Name: More
        Pre: "icon-more"
      # - Name: "Press"
      #   Identifier: "press"
      #   URL: "/press/"
      #   weight: 555
    
      #   Pre: "icon-home"
      # - Name: "Performance"
      #   Identifier: "performance"
      #   URL: "/performance/"
      #   weight: 666
    
      #   Pre: "icon-home"
      # - Name: Investment Philosophy
      #   Identifier: "philosophy"
      #   URL: "/investment-philosophy/"
      #   weight: 777
    
      #   Pre: "icon-home"
  