---
baseURL: http://example.org/
languageCode: en-us
title: Sangam Theme
theme: sangam
themesdir: "../.."
params:
  subtitle: Hugo Theme For Business
  brand_color: "#444"
  contrast_color: ''
menu:
  main:
  - Pre: icon-research
    URL: "/research/"
    Name: Research
    weight: 4
    Identifier: research
  - Pre: icon-about
    URL: "/pages/about/"
    Name: About
    weight: 3
    Identifier: about
  - Pre: icon-contact
    URL: "/pages/contact/"
    Name: Contact
    weight: 5
    Identifier: contact
